#!/system/bin/sh

model=`getprop ro.product.model`
mount -o remount,rw /system
rm /system/usr/keylayout/gpio-keys.kl
if [ "$model" = "LG-LS740" ] || [ "$model" = "LG-LS740" ]; then
	ln -s /system/usr/keylayout/gpio-keys.kl /system/usr/keylayout/gpio-keys.kl 
else
	ln -s /system/usr/keylayout/gpio-keys.kl /system/usr/keylayout/gpio-keys.kl
fi

mount -o remount,ro /system


